### ISSUE TITLE
Using background-position animation is too heavy on browser redraw performance

### ISSUE THREAD

**Issue by imagine10255** [acrool/acrool-react-skeleton#2]
Using background-position animation is too heavy on browser redraw performance

```css
@keyframes skeleton-loading{
    0% {
        background-position: 100% 50%;
    }
    100% {
        background-position: 0 50%;
    }
}
```

change `transform`
